#pragma once

#include "GLFW/glfw3.h"
#include "others/type.hpp"

namespace rin {
enum class key : u16 {
    space         = GLFW_KEY_SPACE,
    apostrophe    = GLFW_KEY_APOSTROPHE,
    comma         = GLFW_KEY_COMMA,
    minus         = GLFW_KEY_MINUS,
    period        = GLFW_KEY_PERIOD,
    slash         = GLFW_KEY_SLASH,
    num0          = GLFW_KEY_0,
    num1          = GLFW_KEY_1,
    num2          = GLFW_KEY_2,
    num3          = GLFW_KEY_3,
    num4          = GLFW_KEY_4,
    num5          = GLFW_KEY_5,
    num6          = GLFW_KEY_6,
    num7          = GLFW_KEY_7,
    num8          = GLFW_KEY_8,
    num9          = GLFW_KEY_9,
    semicolon     = GLFW_KEY_SEMICOLON,
    equal         = GLFW_KEY_EQUAL,
    a             = GLFW_KEY_A,
    b             = GLFW_KEY_B,
    c             = GLFW_KEY_C,
    d             = GLFW_KEY_D,
    e             = GLFW_KEY_E,
    f             = GLFW_KEY_F,
    g             = GLFW_KEY_G,
    h             = GLFW_KEY_H,
    i             = GLFW_KEY_I,
    j             = GLFW_KEY_J,
    k             = GLFW_KEY_K,
    l             = GLFW_KEY_L,
    m             = GLFW_KEY_M,
    n             = GLFW_KEY_N,
    o             = GLFW_KEY_O,
    p             = GLFW_KEY_P,
    q             = GLFW_KEY_Q,
    r             = GLFW_KEY_R,
    s             = GLFW_KEY_S,
    t             = GLFW_KEY_T,
    u             = GLFW_KEY_U,
    v             = GLFW_KEY_V,
    w             = GLFW_KEY_W,
    x             = GLFW_KEY_X,
    y             = GLFW_KEY_Y,
    z             = GLFW_KEY_Z,
    left_bracket  = GLFW_KEY_LEFT_BRACKET,
    backslash     = GLFW_KEY_BACKSLASH,
    right_bracket = GLFW_KEY_RIGHT_BRACKET,
    grave_accent  = GLFW_KEY_GRAVE_ACCENT,
    escape        = GLFW_KEY_ESCAPE,
    enter         = GLFW_KEY_ENTER,
    tab           = GLFW_KEY_TAB,
    backspace     = GLFW_KEY_BACKSPACE,
    insert        = GLFW_KEY_INSERT,
    delete_k      = GLFW_KEY_DELETE,
    right         = GLFW_KEY_RIGHT,
    left          = GLFW_KEY_LEFT,
    down          = GLFW_KEY_DOWN,
    up            = GLFW_KEY_UP,
    page_up       = GLFW_KEY_PAGE_DOWN,
    page_down     = GLFW_KEY_PAGE_DOWN,
    home          = GLFW_KEY_HOME,
    end           = GLFW_KEY_END,
    caps_lock     = GLFW_KEY_CAPS_LOCK,
    scroll_lock   = GLFW_KEY_SCROLL_LOCK,
    num_lock      = GLFW_KEY_NUM_LOCK,
    print_screen  = GLFW_KEY_PRINT_SCREEN,
    pause         = GLFW_KEY_PAUSE,
    f1            = GLFW_KEY_F1,
    f2            = GLFW_KEY_F2,
    f3            = GLFW_KEY_F3,
    f4            = GLFW_KEY_F4,
    f5            = GLFW_KEY_F5,
    f6            = GLFW_KEY_F6,
    f7            = GLFW_KEY_F7,
    f8            = GLFW_KEY_F8,
    f9            = GLFW_KEY_F9,
    f10           = GLFW_KEY_F10,
    f11           = GLFW_KEY_F11,
    f12           = GLFW_KEY_F12,
    f13           = GLFW_KEY_F13,
    f14           = GLFW_KEY_F14,
    f15           = GLFW_KEY_F15,
    f16           = GLFW_KEY_F16,
    f17           = GLFW_KEY_F17,
    f18           = GLFW_KEY_F18,
    f19           = GLFW_KEY_F19,
    f20           = GLFW_KEY_F20,
    f21           = GLFW_KEY_F21,
    f22           = GLFW_KEY_F22,
    f23           = GLFW_KEY_F23,
    f24           = GLFW_KEY_F24,
    f25           = GLFW_KEY_F25,
    kp_0          = GLFW_KEY_KP_0,
    kp_1          = GLFW_KEY_KP_1,
    kp_2          = GLFW_KEY_KP_2,
    kp_3          = GLFW_KEY_KP_3,
    kp_4          = GLFW_KEY_KP_4,
    kp_5          = GLFW_KEY_KP_5,
    kp_6          = GLFW_KEY_KP_6,
    kp_7          = GLFW_KEY_KP_7,
    kp_8          = GLFW_KEY_KP_8,
    kp_9          = GLFW_KEY_KP_9,
    kp_decimal    = GLFW_KEY_KP_DECIMAL,
    kp_divide     = GLFW_KEY_KP_DIVIDE,
    kp_multiply   = GLFW_KEY_KP_MULTIPLY,
    kp_subtract   = GLFW_KEY_KP_SUBTRACT,
    kp_add        = GLFW_KEY_KP_ADD,
    kp_enter      = GLFW_KEY_KP_ENTER,
    kp_equal      = GLFW_KEY_KP_EQUAL,
    left_shift    = GLFW_KEY_LEFT_SHIFT,
    left_control  = GLFW_KEY_LEFT_CONTROL,
    left_alt      = GLFW_KEY_LEFT_ALT,
    left_super    = GLFW_KEY_LEFT_SUPER,
    right_shift   = GLFW_KEY_RIGHT_SHIFT,
    right_control = GLFW_KEY_RIGHT_CONTROL,
    right_alt     = GLFW_KEY_RIGHT_ALT,
    right_super   = GLFW_KEY_RIGHT_SUPER,
    menu          = GLFW_KEY_MENU
};

inline constexpr auto key_space         = key::space;
inline constexpr auto key_apostrophe    = key::apostrophe;
inline constexpr auto key_comma         = key::comma;
inline constexpr auto key_minus         = key::minus;
inline constexpr auto key_period        = key::period;
inline constexpr auto key_slash         = key::slash;
inline constexpr auto key_0             = key::num0;
inline constexpr auto key_1             = key::num1;
inline constexpr auto key_2             = key::num2;
inline constexpr auto key_3             = key::num3;
inline constexpr auto key_4             = key::num4;
inline constexpr auto key_5             = key::num5;
inline constexpr auto key_6             = key::num6;
inline constexpr auto key_7             = key::num7;
inline constexpr auto key_8             = key::num8;
inline constexpr auto key_9             = key::num9;
inline constexpr auto key_semicolon     = key::semicolon;
inline constexpr auto key_equal         = key::equal;
inline constexpr auto key_a             = key::a;
inline constexpr auto key_b             = key::b;
inline constexpr auto key_c             = key::c;
inline constexpr auto key_d             = key::d;
inline constexpr auto key_e             = key::e;
inline constexpr auto key_f             = key::f;
inline constexpr auto key_g             = key::g;
inline constexpr auto key_h             = key::h;
inline constexpr auto key_i             = key::i;
inline constexpr auto key_j             = key::j;
inline constexpr auto key_k             = key::k;
inline constexpr auto key_l             = key::l;
inline constexpr auto key_m             = key::m;
inline constexpr auto key_n             = key::n;
inline constexpr auto key_o             = key::o;
inline constexpr auto key_p             = key::p;
inline constexpr auto key_q             = key::q;
inline constexpr auto key_r             = key::r;
inline constexpr auto key_s             = key::s;
inline constexpr auto key_t             = key::t;
inline constexpr auto key_u             = key::u;
inline constexpr auto key_v             = key::v;
inline constexpr auto key_w             = key::w;
inline constexpr auto key_x             = key::x;
inline constexpr auto key_y             = key::y;
inline constexpr auto key_z             = key::z;
inline constexpr auto key_left_bracket  = key::left_bracket;
inline constexpr auto key_backslash     = key::backslash;
inline constexpr auto key_right_bracket = key::right_bracket;
inline constexpr auto key_grave_accent  = key::grave_accent;
inline constexpr auto key_escape        = key::escape;
inline constexpr auto key_enter         = key::enter;
inline constexpr auto key_tab           = key::tab;
inline constexpr auto key_backspace     = key::backspace;
inline constexpr auto key_insert        = key::insert;
inline constexpr auto key_delete        = key::delete_k;
inline constexpr auto key_right         = key::right;
inline constexpr auto key_left          = key::left;
inline constexpr auto key_down          = key::down;
inline constexpr auto key_up            = key::up;
inline constexpr auto key_page_up       = key::page_up;
inline constexpr auto key_page_down     = key::page_down;
inline constexpr auto key_home          = key::home;
inline constexpr auto key_end           = key::end;
inline constexpr auto key_caps_lock     = key::caps_lock;
inline constexpr auto key_scroll_lock   = key::scroll_lock;
inline constexpr auto key_num_lock      = key::num_lock;
inline constexpr auto key_print_screen  = key::print_screen;
inline constexpr auto key_pause         = key::pause;
inline constexpr auto key_f1            = key::f1;
inline constexpr auto key_f2            = key::f2;
inline constexpr auto key_f3            = key::f3;
inline constexpr auto key_f4            = key::f4;
inline constexpr auto key_f5            = key::f5;
inline constexpr auto key_f6            = key::f6;
inline constexpr auto key_f7            = key::f7;
inline constexpr auto key_f8            = key::f8;
inline constexpr auto key_f9            = key::f9;
inline constexpr auto key_f10           = key::f10;
inline constexpr auto key_f11           = key::f11;
inline constexpr auto key_f12           = key::f12;
inline constexpr auto key_f13           = key::f13;
inline constexpr auto key_f14           = key::f14;
inline constexpr auto key_f15           = key::f15;
inline constexpr auto key_f16           = key::f16;
inline constexpr auto key_f17           = key::f17;
inline constexpr auto key_f18           = key::f18;
inline constexpr auto key_f19           = key::f19;
inline constexpr auto key_f20           = key::f20;
inline constexpr auto key_f21           = key::f21;
inline constexpr auto key_f22           = key::f22;
inline constexpr auto key_f23           = key::f23;
inline constexpr auto key_f24           = key::f24;
inline constexpr auto key_f25           = key::f25;
inline constexpr auto keypad_0          = key::kp_0;
inline constexpr auto keypad_1          = key::kp_1;
inline constexpr auto keypad_2          = key::kp_2;
inline constexpr auto keypad_3          = key::kp_3;
inline constexpr auto keypad_4          = key::kp_4;
inline constexpr auto keypad_5          = key::kp_5;
inline constexpr auto keypad_6          = key::kp_6;
inline constexpr auto keypad_7          = key::kp_7;
inline constexpr auto keypad_8          = key::kp_8;
inline constexpr auto keypad_9          = key::kp_9;
inline constexpr auto keypad_decimal    = key::kp_decimal;
inline constexpr auto keypad_divide     = key::kp_divide;
inline constexpr auto keypad_multiply   = key::kp_multiply;
inline constexpr auto keypad_subtract   = key::kp_subtract;
inline constexpr auto keypad_add        = key::kp_add;
inline constexpr auto keypad_enter      = key::kp_enter;
inline constexpr auto keypad_equal      = key::kp_equal;
inline constexpr auto key_left_shift    = key::left_shift;
inline constexpr auto key_left_control  = key::left_control;
inline constexpr auto key_left_alt      = key::left_alt;
inline constexpr auto key_left_super    = key::left_super;
inline constexpr auto key_right_shift   = key::right_shift;
inline constexpr auto key_right_control = key::right_control;
inline constexpr auto key_right_alt     = key::right_alt;
inline constexpr auto key_right_super   = key::right_super;
inline constexpr auto key_menu          = key::menu;
}  // namespace rin